### ISSUE TITLE
CudaAllocator在Windows MSVC上编译错误的问题

### ISSUE THREAD

**Issue by busyyang** [parallel101/hw08#11]
你好，我发现你实现的这个CudaAllocator是好用的CUDA内存管理工具，我尝试将CudaAllocator.h文件拷贝到我的工程中，并写了一个非常简单测试函数：
~~~cpp
#include <string>
#include <vector>
#include <iostream>
#include <cuda_runtime.h>
#include "CudaAllocator.h"

__global__ void TestVectorKernel(int *x, int n)
{
	int idx = threadIdx.x + blockIdx.x * blockDim.x;
	if (idx < n)
	{
		x[idx] = idx + 1;
	}
}
~~~

然后在一个函数中创建CudaAllocator的std::vector，并调用这个核函数。
~~~cpp
int main()
{
	
	int N = 3;
	std::vector<int, CudaAllocator<int>> arr(N);
	TestVectorKernel <<<1, 4 >>> (arr.data(), N);
	checkCudaErrors(cudaDeviceSynchronize());
	for (size_t i = 0; i < N; i++)
	{
		std::cout << arr[i] << std::endl;
	}
	return 0;
}
~~~

但是在编译的时候出现问题：
~~~
Build started...
1>------ Build started: Project: Project2, Configuration: Debug x64 ------
1>Compiling CUDA source file Source.cpp...
1>
1>C:\Users\user\source\repos\cuda_test\Project2>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute_52\" --use-local-env -ccbin "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64" -x cu -rdc=true  -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include"  -G   --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile -cudart static -allow-unsupported-compiler -g   -D_DEBUG -D_CONSOLE -D_UNICODE -DUNICODE -Xcompiler "/EHsc /W3 /nologo /Od /Fdx64\Debug\vc143.pdb /FS /Zi /RTC1 /MDd " -o x64\Debug\Source.cpp.obj "C:\Users\user\source\repos\cuda_test\Project2\Source.cpp"
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\vector(1908): error : no suitable user-defined conversion from "std::_Rebind_alloc_t<CudaAllocator<int>, int>" to "std::_Rebind_alloc_t<std::_Rebind_alloc_t<CudaAllocator<int>, int>, std::_Container_proxy>" exists
1>          detected during:
1>            instantiation of "void std::vector<_Ty, _Alloc>::_Construct_n(std::vector<_Ty, _Alloc>::size_type, _Valty &&...) [with _Ty=int, _Alloc=CudaAllocator<int>, _Valty=<>]"
1>(669): here
1>            instantiation of "std::vector<_Ty, _Alloc>::vector(std::vector<_Ty, _Alloc>::size_type, const _Alloc &) [with _Ty=int, _Alloc=CudaAllocator<int>]"
1>C:/Users/user/source/repos/cuda_test/Project2/Source.cpp(34): here
1>
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\vector(793): error : no suitable user-defined conversion from "std::_Rebind_alloc_t<CudaAllocator<int>, int>" to "std::_Rebind_alloc_t<std::_Rebind_alloc_t<CudaAllocator<int>, int>, std::_Container_proxy>" exists
1>          detected during instantiation of "std::vector<_Ty, _Alloc>::~vector() [with _Ty=int, _Alloc=CudaAllocator<int>]"
1>C:/Users/user/source/repos/cuda_test/Project2/Source.cpp(34): here
1>
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\vector(794): error : no instance of function template "std::_Delete_plain_internal" matches the argument list
1>            argument types are: (<error-type>, std::_Container_proxy *)
1>          detected during instantiation of "std::vector<_Ty, _Alloc>::~vector() [with _Ty=int, _Alloc=CudaAllocator<int>]"
1>C:/Users/user/source/repos/cuda_test/Project2/Source.cpp(34): here
1>
1>3 errors detected in the compilation of "C:/Users/user/source/repos/cuda_test/Project2/Source.cpp".
1>Source.cpp
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\BuildCustomizations\CUDA 11.1.targets(785,9): error MSB3721: The command ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute_52\" --use-local-env -ccbin "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64" -x cu -rdc=true  -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include"  -G   --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile -cudart static -allow-unsupported-compiler -g   -D_DEBUG -D_CONSOLE -D_UNICODE -DUNICODE -Xcompiler "/EHsc /W3 /nologo /Od /Fdx64\Debug\vc143.pdb /FS /Zi /RTC1 /MDd " -o x64\Debug\Source.cpp.obj "C:\Users\user\source\repos\cuda_test\Project2\Source.cpp"" exited with code 1.
1>Done building project "Project2.vcxproj" -- FAILED.
~~~

我这边的环境是：
 - Windows 11 x64
 - Visual Studio 2022
 - CUDA 11.1
 

不太明白哪里出现了问题，是否可以麻烦看一下，或者有没有其他也遇到这个问题的同学解答一下。

**Comment by lijunliangTG** [comment]
`template  <class T>
struct  CudaAllocator{
    using value_type = T;
    CudaAllocator() = default;
    template <class U> CudaAllocator(const CudaAllocator<U>&) {}
    T* allocate(std::size_t n) {
        T* ptr;
        cudaMallocManaged(&ptr, n * sizeof(T));
        return ptr;
    }
    void deallocate(T* p, std::size_t n) {
        cudaFree(p);
    }

};`

可以试一下这样写

**Comment by busyyang** [comment]
还是不行，我这里换了CUDA11.7版本，编译的时候报错变了：
~~~
Build started...
1>------ Build started: Project: Project2, Configuration: Debug x64 ------
1>Compiling CUDA source file CudaAllocator.h...
1>Compiling CUDA source file Source.cpp...
1>
1>C:\Users\YangJie\source\repos\cuda_test\Project2>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute_52\" --use-local-env -ccbin "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64" -x cu -rdc=true  -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include"  -G   --keep-dir x64\Debug  -maxrregcount=0  --machine 64 --compile -cudart static -allow-unsupported-compiler -g  -D_DEBUG -D_CONSOLE -D_UNICODE -DUNICODE -Xcompiler "/EHsc /W3 /nologo /Od /Fdx64\Debug\vc143.pdb /FS /Zi /RTC1 /MDd " -o C:\Users\user\source\repos\cuda_test\Project2\x64\Debug\CudaAllocator.h.obj "C:\Users\user\source\repos\cuda_test\Project2\CudaAllocator.h"
1>
1>C:\Users\user\source\repos\cuda_test\Project2>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute_52\" --use-local-env -ccbin "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64" -x cu -rdc=true  -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include"  -G   --keep-dir x64\Debug  -maxrregcount=0  --machine 64 --compile -cudart static -allow-unsupported-compiler -g  -D_DEBUG -D_CONSOLE -D_UNICODE -DUNICODE -Xcompiler "/EHsc /W3 /nologo /Od /Fdx64\Debug\vc143.pdb /FS /Zi /RTC1 /MDd " -o C:\Users\user\source\repos\cuda_test\Project2\x64\Debug\Source.cpp.obj "C:\Users\user\source\repos\cuda_test\Project2\Source.cpp"
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\vector(2125): error : no suitable user-defined conversion from "CudaAllocator<int>" to "CudaAllocator<std::_Container_proxy>" exists
1>          detected during:
1>            instantiation of "void std::vector<_Ty, _Alloc>::_Construct_n(std::vector<_Ty, _Alloc>::size_type, _Valty &&...) [with _Ty=int, _Alloc=CudaAllocator<int>, _Valty=<>]"
1>(683): here
1>            instantiation of "std::vector<_Ty, _Alloc>::vector(std::vector<_Ty, _Alloc>::size_type, const _Alloc &) [with _Ty=int, _Alloc=CudaAllocator<int>]"
1>C:\Users\user\source\repos\cuda_test\Project2\Source.cpp(33): here
1>
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\vector(832): error : no suitable user-defined conversion from "CudaAllocator<int>" to "CudaAllocator<std::_Container_proxy>" exists
1>          detected during instantiation of "std::vector<_Ty, _Alloc>::~vector() [with _Ty=int, _Alloc=CudaAllocator<int>]"
1>C:\Users\user\source\repos\cuda_test\Project2\Source.cpp(33): here
1>
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\vector(833): error : no instance of function template "std::_Delete_plain_internal" matches the argument list
1>            argument types are: (<error-type>, std::_Container_proxy *)
1>          detected during instantiation of "std::vector<_Ty, _Alloc>::~vector() [with _Ty=int, _Alloc=CudaAllocator<int>]"
1>C:\Users\user\source\repos\cuda_test\Project2\Source.cpp(33): here
1>
1>3 errors detected in the compilation of "C:/Users/YangJie/source/repos/cuda_test/Project2/Source.cpp".
1>Source.cpp
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\BuildCustomizations\CUDA 11.7.targets(790,9): error MSB3721: The command ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute_52\" --use-local-env -ccbin "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64" -x cu -rdc=true  -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include"  -G   --keep-dir x64\Debug  -maxrregcount=0  --machine 64 --compile -cudart static -allow-unsupported-compiler -g  -D_DEBUG -D_CONSOLE -D_UNICODE -DUNICODE -Xcompiler "/EHsc /W3 /nologo /Od /Fdx64\Debug\vc143.pdb /FS /Zi /RTC1 /MDd " -o C:\Users\user\source\repos\cuda_test\Project2\x64\Debug\Source.cpp.obj "C:\Users\user\source\repos\cuda_test\Project2\Source.cpp"" exited with code 1.
1>Done building project "Project2.vcxproj" -- FAILED.
1>CudaAllocator.h
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Elapsed 00:02.737 ==========
~~~

**Comment by archibate** [comment]
建议卸载wendous











无法顺畅的大口呼吸，是活着的最好证明

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月20日(周二) 下午5:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [parallel101/hw08] CudaAllocator在Windows MSVC上编译错误的问题 (Issue #11)




 
还是不行，我这里换了CUDA11.7版本，编译的时候报错变了：
 Build started... 1&gt;------ Build started: Project: Project2, Configuration: Debug x64 ------ 1&gt;Compiling CUDA source file CudaAllocator.h... 1&gt;Compiling CUDA source file Source.cpp... 1&gt; 1&gt;C:\Users\YangJie\source\repos\cuda_test\Project2&gt;"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute_52\" --use-local-env -ccbin "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64" -x cu -rdc=true  -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include"  -G   --keep-dir x64\Debug  -maxrregcount=0  --machine 64 --compile -cudart static -allow-unsupported-compiler -g  -D_DEBUG -D_CONSOLE -D_UNICODE -DUNICODE -Xcompiler "/EHsc /W3 /nologo /Od /Fdx64\Debug\vc143.pdb /FS /Zi /RTC1 /MDd " -o C:\Users\user\source\repos\cuda_test\Project2\x64\Debug\CudaAllocator.h.obj "C:\Users\user\source\repos\cuda_test\Project2\CudaAllocator.h" 1&gt; 1&gt;C:\Users\user\source\repos\cuda_test\Project2&gt;"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute_52\" --use-local-env -ccbin "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64" -x cu -rdc=true  -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include"  -G   --keep-dir x64\Debug  -maxrregcount=0  --machine 64 --compile -cudart static -allow-unsupported-compiler -g  -D_DEBUG -D_CONSOLE -D_UNICODE -DUNICODE -Xcompiler "/EHsc /W3 /nologo /Od /Fdx64\Debug\vc143.pdb /FS /Zi /RTC1 /MDd " -o C:\Users\user\source\repos\cuda_test\Project2\x64\Debug\Source.cpp.obj "C:\Users\user\source\repos\cuda_test\Project2\Source.cpp" 1&gt;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\vector(2125): error : no suitable user-defined conversion from "CudaAllocator<int&gt;" to "CudaAllocator<std::_Container_proxy&gt;" exists 1&gt;          detected during: 1&gt;            instantiation of "void std::vector<_Ty, _Alloc&gt;::_Construct_n(std::vector<_Ty, _Alloc&gt;::size_type, _Valty &amp;&amp;...) [with _Ty=int, _Alloc=CudaAllocator<int&gt;, _Valty=<&gt;]" 1&gt;(683): here 1&gt;            instantiation of "std::vector<_Ty, _Alloc&gt;::vector(std::vector<_Ty, _Alloc&gt;::size_type, const _Alloc &amp;) [with _Ty=int, _Alloc=CudaAllocator<int&gt;]" 1&gt;C:\Users\user\source\repos\cuda_test\Project2\Source.cpp(33): here 1&gt; 1&gt;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\vector(832): error : no suitable user-defined conversion from "CudaAllocator<int&gt;" to "CudaAllocator<std::_Container_proxy&gt;" exists 1&gt;          detected during instantiation of "std::vector<_Ty, _Alloc&gt;::~vector() [with _Ty=int, _Alloc=CudaAllocator<int&gt;]" 1&gt;C:\Users\user\source\repos\cuda_test\Project2\Source.cpp(33): here 1&gt; 1&gt;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\vector(833): error : no instance of function template "std::_Delete_plain_internal" matches the argument list 1&gt;            argument types are: (<error-type&gt;, std::_Container_proxy *) 1&gt;          detected during instantiation of "std::vector<_Ty, _Alloc&gt;::~vector() [with _Ty=int, _Alloc=CudaAllocator<int&gt;]" 1&gt;C:\Users\user\source\repos\cuda_test\Project2\Source.cpp(33): here 1&gt; 1&gt;3 errors detected in the compilation of "C:/Users/YangJie/source/repos/cuda_test/Project2/Source.cpp". 1&gt;Source.cpp 1&gt;C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\BuildCustomizations\CUDA 11.7.targets(790,9): error MSB3721: The command ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute_52\" --use-local-env -ccbin "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64" -x cu -rdc=true  -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include"  -G   --keep-dir x64\Debug  -maxrregcount=0  --machine 64 --compile -cudart static -allow-unsupported-compiler -g  -D_DEBUG -D_CONSOLE -D_UNICODE -DUNICODE -Xcompiler "/EHsc /W3 /nologo /Od /Fdx64\Debug\vc143.pdb /FS /Zi /RTC1 /MDd " -o C:\Users\user\source\repos\cuda_test\Project2\x64\Debug\Source.cpp.obj "C:\Users\user\source\repos\cuda_test\Project2\Source.cpp"" exited with code 1. 1&gt;Done building project "Project2.vcxproj" -- FAILED. 1&gt;CudaAllocator.h ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ========== ========== Elapsed 00:02.737 ==========

**Comment by busyyang** [comment]
公司电脑不是想卸载就卸载(╯‵□′)╯︵┻━┻

**Comment by sailing-innocent** [comment]
今天也遇到了类似的问题，课程中给出的代码已经不能跑了。需要自己修改定义一下CudaAllocator<_Other>模板的构造，应该是标准库对新特性的支持导致旧的崩了……

给一个能用的Allocator例子，关键就是手动把其他模板的构造函数定义一下，定义成空的就好。

```cuda
template <class T>
struct CudaAllocator {
    using value_type = T;
    CudaAllocator() = default;
    //**** ADD THIS MANURALLY ****
    template<class _Other>
    constexpr CudaAllocator(const CudaAllocator<_Other>&) noexcept {}

    T *allocate(size_t size) {
        T *ptr = nullptr;
        cudaMallocManaged(&ptr, size * sizeof(T));
        return ptr;
    }

    void deallocate(T *ptr, size_t size = 0) {
        cudaFree(ptr);
    }
};

```

**Comment by busyyang** [comment]
> 

感谢，这个方式的确可以。

**Comment by TycheLime** [comment]
我目前也遇到了一个问题就是这串示例代码，似乎已经在新版本遇到了兼容性问题。我该如何改写呢？
template<int N,typename T>
__global__ void kernel(T* arr) {
    for (int i = blockDim.x * blockIdx.x + threadIdx; i < N; i += blockDim.x * gridDim.x) {
        arr[i] = i;
    }
}

**Comment by tiandixuanhuang1** [comment]
> 今天也遇到了类似的问题，课程中给出的代码已经不能跑了。需要自己修改定义一下CudaAllocator<_Other>模板的构造，应该是标准库对新特性的支持导致旧的崩了……
> 
> 给一个能用的Allocator例子，关键就是手动把其他模板的构造函数定义一下，定义成空的就好。
> 
> ```cuda-c++
> template <class T>
> struct CudaAllocator {
>     using value_type = T;
>     CudaAllocator() = default;
>     //**** ADD THIS MANURALLY ****
>     template<class _Other>
>     constexpr CudaAllocator(const CudaAllocator<_Other>&) noexcept {}
> 
>     T *allocate(size_t size) {
>         T *ptr = nullptr;
>         cudaMallocManaged(&ptr, size * sizeof(T));
>         return ptr;
>     }
> 
>     void deallocate(T *ptr, size_t size = 0) {
>         cudaFree(ptr);
>     }
> };
> ```

我使用的CUDA 11.8，如果按照这位老哥的还有报错，将这份代码中
`CudaAllocator() = defalut;`
改为
`CudaAllocator(){}`

**Comment by TycheLime** [comment]
谢谢~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "parallel101/hw08"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月14日(星期四) 上午10:41
***@***.***&gt;;
抄送:&nbsp;"Fox ***@***.******@***.***&gt;;
主题:&nbsp;Re: [parallel101/hw08] CudaAllocator在Windows MSVC上编译错误的问题 (Issue #11)





  
今天也遇到了类似的问题，课程中给出的代码已经不能跑了。需要自己修改定义一下CudaAllocator<_Other&gt;模板的构造，应该是标准库对新特性的支持导致旧的崩了……
 
给一个能用的Allocator例子，关键就是手动把其他模板的构造函数定义一下，定义成空的就好。
 template <class T&gt; struct CudaAllocator {     using value_type = T;     CudaAllocator() = default;     //**** ADD THIS MANURALLY ****     template<class _Other&gt;     constexpr CudaAllocator(const CudaAllocator<_Other&gt;&amp;) noexcept {}     T *allocate(size_t size) {         T *ptr = nullptr;         cudaMallocManaged(&amp;ptr, size * sizeof(T));         return ptr;     }     void deallocate(T *ptr, size_t size = 0) {         cudaFree(ptr);     } };   
我使用的CUDA 11.8，如果按照这位老哥的还有报错，将这份代码中
 CudaAllocator() = defalut;
 改为
 CudaAllocator(){}
